# Generated by Django 3.1.3 on 2021-05-13 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('1Web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='tipo_categoria',
            field=models.IntegerField(choices=[[0, 'Guitarras'], [1, 'Bajos'], [2, 'Pianos'], [3, 'Baterias Acusticas'], [4, 'Bateria Electronica'], [5, 'Cabezales'], [6, 'Audifonos'], [7, 'Monitores'], [8, 'Parlantes'], [9, 'Cables'], [10, 'Microfonos'], [11, 'Interfaces'], [12, 'Mixers']]),
        ),
    ]
